//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> NumberOfTickets { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<bool> IsVerifiedPayment { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
