//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpsilonHost
    {
        public int AddressId { get; set; }
        public string Address { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PortNumber { get; set; }
        public bool AddressFlag { get; set; }
        public bool Current { get; set; }
    }
}
