//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpsilonKey
    {
        public int KeyId { get; set; }
        public int UserId { get; set; }
        public byte[] PublicKey { get; set; }
        public byte[] PrivateKey { get; set; }
        public bool Current { get; set; }
        public byte[] TrippleDESKey { get; set; }
        public int RSAStrength { get; set; }
        public byte[] Modulus { get; set; }
        public Nullable<int> EncryptTypeId { get; set; }
    
        public virtual EpsilonKey EpsilonKeys1 { get; set; }
        public virtual EpsilonKey EpsilonKey1 { get; set; }
    }
}
