//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumReview
    {
        public int id { get; set; }
        public string forum { get; set; }
        public string reviews { get; set; }
        public Nullable<bool> forum_flag { get; set; }
        public Nullable<bool> review_flag { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> timePosted { get; set; }
        public string userid { get; set; }
    }
}
