//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrder
    {
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> order_id_fk { get; set; }
        public Nullable<int> numberOrdered { get; set; }
        public int itemId { get; set; }
        public string product_name { get; set; }
    }
}
