//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string username { get; set; }
        public string password { get; set; }
        public string roles { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public Nullable<System.DateTime> validDate { get; set; }
        public int UserId { get; set; }
    }
}
