//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<decimal> order_gross { get; set; }
        public string email { get; set; }
        public Nullable<bool> paid_for { get; set; }
    }
}
