//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public Nullable<int> PropertyNumber { get; set; }
        public Nullable<decimal> CrossArea { get; set; }
        public Nullable<decimal> YieldStress { get; set; }
        public Nullable<decimal> PlasticMod { get; set; }
        public Nullable<decimal> YoungsMod { get; set; }
        public Nullable<decimal> SecondMomArea { get; set; }
    }
}
