//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOP_PRODS
    {
        public string prodId { get; set; }
        public string prodName { get; set; }
        public decimal prodPrice { get; set; }
        public string prodDesc { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> numberOfVoters { get; set; }
    }
}
