//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int TicketId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<System.Guid> TicketGUID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Event Event { get; set; }
    }
}
