// <auto-generated />
namespace EntertainmentTicketMaster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class EntityFrameWorkUpdateV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityFrameWorkUpdateV2));
        
        string IMigrationMetadata.Id
        {
            get { return "201506201701054_EntityFrameWorkUpdateV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
